kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "event-log-collector.fullname" . }}
  annotations:
{{ toYaml .Values.configmap.annotations | indent 4 }}   
  labels:
{{ include "event-log-collector.labels" . | indent 4 }}
data:
{{- range $name, $config := .Values.eventLogCollector.config }}
  {{ $name }}: |-
{{ tpl $config $ | indent 4 }}
  {{- end }}
