{
 "title": "Event Log Collector Dashboard",
 "description": "Event Log Collector Monitoring Dashboard",
 "tags": [
  "event-log-collector",
  "v2.x.x"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "topic", "query": { "query": "label_values(topic)" } }
  ]
 },
 "panels": [
  {
   "title": "Event Log Collector Components",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Partitions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elc_partitions_total{instance=~\"elc-log-fetcher(.*)\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Event Log Backlog per Partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elc_fetcher_offset_behind{instance=~\"elc-log-fetcher(.*)\", topic=\"$topic\"}) by (topic, partition)",
     "legendFormat": "{{topic}} (p{{partition}})"
    },
    {
     "expr": "sum(elc_fetcher_offset_behind{instance=~\"elc-log-fetcher(.*)\", topic=\"$topic\"}) by (topic)",
     "legendFormat": "{{topic}}-Total"
    }
   ]
  },
  {
   "title": "Processing Errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elc_processing_errors{topic=~\"$topic\"}) by (service, code, message)",
     "legendFormat": "{{service}}: {{code}}"
    }
   ]
  },
  {
   "title": "Total Logs Processed",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elc_processing_total{instance=~\"^($instance)$\", topic=~\"^($topic)$\"}) by (topic, component, status, code, message)",
     "legendFormat": "{{component}}: {{message}}"
    },
    {
     "expr": "sum(elc_processing_total{instance=~\"^($instance)$\", topic=~\"^($topic)$\"}) by (topic)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Logs Processed",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elc_processing_total{instance=~\"^($instance)$\", topic=~\"^($topic)$\"}) by (component, status, code, message)",
     "legendFormat": "{{component}}: {{message}}"
    }
   ]
  },
  {
   "title": "Log Processing Duration (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(elc_message_processing_duration{instance=~\"^($instance)$\", topic=~\"^($topic)$\"}) by (component, status, code, message)",
     "legendFormat": "{{component}} | {{status}} | {{message}}"
    }
   ]
  },
  {
   "title": "Total Records In",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elc_num_records_in{instance=~\"^($instance)$\", topic=~\"^($topic)$\"}) by (topic, component)",
     "legendFormat": "{{topic}}: {{component}}"
    }
   ]
  },
  {
   "title": "Total Records Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elc_num_records_out{instance=~\"^($instance)$\", topic=~\"^($topic)$\"}) by (topic, component)",
     "legendFormat": "{{topic}}: {{component}}"
    }
   ]
  },
  {
   "title": "Total Records In / Out (Fetcher)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elc_num_records_in{instance=~\"^($instance)$\", topic=~\"^($topic)$\", component=\"fetcher\"}) by (topic)",
     "legendFormat": "in"
    },
    {
     "expr": "sum(elc_num_records_out{instance=~\"^($instance)$\", topic=~\"^($topic)$\", component=\"fetcher\"}) by (topic)",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Total Records In / Out (Processor)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elc_num_records_in{instance=~\"^($instance)$\", topic=~\"^($topic)$\", component=\"processor\"}) by (topic)",
     "legendFormat": "in"
    },
    {
     "expr": "sum(elc_num_records_out{instance=~\"^($instance)$\", topic=~\"^($topic)$\", component=\"processor\"}) by (topic)",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Total Records In / Out (Writer)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elc_num_records_in{instance=~\"$instance\", topic=\"$topic\", component=\"writer\"}) by (topic)",
     "legendFormat": "in"
    },
    {
     "expr": "sum(elc_num_records_out{instance=~\"$instance\", topic=\"$topic\", component=\"writer\"}) by (topic)",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Avg Lag In",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(elc_lag_in{instance=~\"^($instance)$\", topic=~\"^($topic)$\"}) by (topic, component)",
     "legendFormat": "{{topic}}: {{component}}"
    }
   ]
  },
  {
   "title": "Avg Lag Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(elc_lag_out{instance=~\"^($instance)$\", topic=~\"^($topic)$\"}) by (topic, component)",
     "legendFormat": "{{topic}}: {{component}}"
    }
   ]
  },
  {
   "title": "Component Read Throughput ( op/s )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elc_num_records_in{instance=~\"^($instance)$\", topic=~\"^($topic)$\"}[1m])) by (topic, component)",
     "legendFormat": "{{topic}}: {{component}}"
    }
   ]
  },
  {
   "title": "Consumer Read Increase ( op/m ) ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(elc_num_records_in{instance=~\"^($instance)$\", topic=~\"^($topic)$\"}[1m])) by (topic, component)",
     "legendFormat": "{{topic}}: {{component}}"
    }
   ]
  },
  {
   "title": "Storage Provider Write Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Storage Provider Writes in Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elc_elasticsearch_commit_total{instance=~\"^($instance)$\"}) by (code)",
     "legendFormat": "Elasticsearch: {{code}}"
    },
    {
     "expr": "sum(elc_log_writes_total{instance=~\"^($instance)$\"}) by (processor, code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ElasticSearch / OpenSearch Write Success Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elc_elasticsearch_commit_total{code=~\"2..\", instance=~\"^($instance)$\"})"
    },
    {
     "expr": "sum(elc_opensearch_commit_total{code=~\"2..\", instance=~\"^($instance)$\"})"
    }
   ]
  },
  {
   "title": "ElasticSearch / OpensSearch  Write Failure Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elc_elasticsearch_commit_total{code!~\"2..\", instance=~\"^($instance)$\"}) by (code)",
     "legendFormat": "{{code}}: {{message}}"
    },
    {
     "expr": "sum(elc_opensearch_commit_total{code!~\"2..\", instance=~\"^($instance)$\"}) by (code)",
     "legendFormat": "{{code}}: {{message}}"
    }
   ]
  },
  {
   "title": "Storage Average Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(elc_commit_duration_seconds_sum{instance=~\"^($instance)$\"} / elc_commit_duration_seconds_count{instance=~\"^($instance)$\"})",
     "legendFormat": "Elasticsearch"
    },
    {
     "expr": "elc_storage_write_duration_seconds{instance=~\"^($instance)$\"} / elc_storage_write_duration_seconds{instance=~\"^($instance)$\"}",
     "legendFormat": "filesystem"
    }
   ]
  },
  {
   "title": "Storage Provider Write Throughput ( op/s ) ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elc_elasticsearch_commit_total{instance=~\"^($instance)$\"}[1m])) by (code)",
     "legendFormat": "Elasticsearch ({{code}})"
    },
    {
     "expr": "sum(rate(elc_log_writes_total{instance=~\"^($instance)$\"}[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Storage Provider Writes Increase ( op/m )",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(elc_elasticsearch_commit_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (code)",
     "legendFormat": "Elasticsearch ({{code}})"
    },
    {
     "expr": "sum(increase(elc_log_writes_total{instance=~\"^($instance)$\"}[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{}[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_total_bytes{instance=~\"^($instance)$\"}) by (instance)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Http Requests",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "sum(elc_http_requests_total{instance=~\"$instance\"}) by (http_url,http_response_status)",
     "legendFormat": "{{http_url}}, {{http_response_status}}"
    }
   ]
  },
  {
   "title": "Http Response Code 2XX Total ",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 142 },
   "targets": [
    {
     "expr": "sum(elc_http_requests_total{http_response_code=~\"2..\",instance=~\"$instance\"}) by (http_url)",
     "legendFormat": "URL: {{http_url}}"
    }
   ]
  },
  {
   "title": "Http Response Code 3/4/5XX Total ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 152 },
   "targets": [
    {
     "expr": "sum(elc_http_requests_total{http_response_code!~\"2..\",cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}) by (pod, http_url,http_response_code)"
    }
   ]
  },
  {
   "title": "Http Request Duration in Seconds - Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elc_http_request_duration_seconds_current{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Go Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"^($instance)$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 168 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"^($instance)$\"}",
     "legendFormat": " {{quantile}}"
    }
   ]
  }
 ]
}