version: '3'

services:

  elc-log-fetcher:
    build: .
    container_name: elc-log-fetcher
    restart: unless-stopped
    environment:
      - ELC_CLIENT_ID=$ELC_CLIENT_ID
      - ELC_CLIENT_SECRET=$ELC_CLIENT_SECRET
      - ELC_ENABLE_MONITORING=1
    depends_on:
      - kafka
    volumes:
      - ${PWD}/configs/config.distributed-docker-compose.yaml:/nuance/configs/config.yaml
    entrypoint: [ "./bin/event-log-fetcher", "-c", "configs/config.yaml" ]
    security_opt:
      - no-new-privileges:true
    networks:
      - event-log-collector

networks:
  event-log-collector:
    driver: bridge