apiVersion: 1

deleteDatasources:
  - name: prometheus
    orgId: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    password:
    user:
    database:
    basicAuth: true
    basicAuthUser: admin
    basicAuthPassword: foobar
    withCredentials:
    isDefault:
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:
      tlsCaCert: "..."
      tlsClientCert: "..."
      tlsClientKey: "..."
    version: 1
    editable: true