processor:
    name: mix-default
    config:
        filter:
            type: blacklist # blacklist or whitelist
            content_type:   # filter out some of the ASR event logs to reduce noise and storage space required
                - application/x-nuance-asr-statusresponse*
                - application/x-nuance-asr-startspeechresponse*
                - application/x-nuance-asr-partialresultresponse*
                - application/x-nuance-asr-finalresultresponse*
        cache:
            type: redis
            # parameters for redis cache
            addr: localhost:6379 # Default value is redis:6379
            # db: # Default value is 0
            # default_ttl: # Default value is 900
            # password: # Default value is empty

writer:
    name: opensearch
    # config:
        ### Required Parameters

        # none

        ### Optional Parameters
        
        # index_prefix: # Default value is set to mix3-logs-v2
        # refresh: # Default value is true
        # addresses:
            # - http://localhost:9200   # this is the default

        # num_workers: 50   # Num Workers specifies how many event logs can be processed in parallel by log writer
        # rate_limit:       # Rate Limit controls how fast event logs can be written to storage
            # limit: 1000
            # burst: 10

pipeline:
    storage_provider: kafka
    fetcher:
        writer:
            ## Required
            hosts:
                - 127.0.0.1:9092                
            topic: queues.fetcher
    processor:
        reader:                
            ## Required
            hosts:
                - 127.0.0.1:9092
            group: elc
            topic: queues.fetcher

            ## Optional                
            # offset: earliest # default is none
            # auto_commit_offset_enabled: false # default is true

        writer:
            ## Required
            hosts:
                - 127.0.0.1:9092
            topic: queues.processor                
    writer:
        reader:
            ## Required
            hosts:
                - 127.0.0.1:9092                
            group: elc
            topic: queues.processor

            ## Optional                
            # offset: earliest # default is none
            # auto_commit_offset_enabled: false # default is true
