writer:
    name: mix-log-producer-api
    # config:
        ### Required Parameters

        # none

        ### Optional Parameters

        # credentials:
            # client_id:  # Provide a "Mix Client ID" or pass in with ELC_CLIENT_ID env var
            # client_secret: # Provide a "Mix Client Secret" or pass in with ELC_CLIENT_SECRET env var
        # mix_log_producer_api_url: # Default value is https://log.api.nuance.com/producers

        # num_workers: 50   # Num Workers specifies how many event logs can be processed in parallel by log writer
        # rate_limit:       # Rate Limit controls how fast event logs can be written to storage
            # limit: 1000
            # burst: 10
        # max_retries: 10   # Number of attempts to try and write to storage before failing
        # delay: 10         # Amount of time, in seconds, to wait to retry a failed write to storage

pipeline:
    storage_provider: kafka
    writer:
        reader:
            ## Required
            hosts:
                - 127.0.0.1:9092                
            group: elc
            topic: queues.processor

            ## Optional                
            offset: earliest # default is none
            # auto_commit_offset_enabled: false # default is true
