processor:
    name: mix-default
    config:
        cache:
            type: redis
            # parameters for redis cache
            addr: localhost:6379 # Default value is redis:6379
            # db: # Default value is 0
            # default_ttl: # Default value is 900
            # password: # Default value is empty

pipeline:
    storage_provider: kafka
    fetcher:
        writer:
            ## Required
            hosts:
                - 127.0.0.1:9092                
            topic: queues.fetcher
    processor:
        reader:                
            ## Required
            hosts:
                - 127.0.0.1:9092
            group: elc
            topic: queues.fetcher

            ## Optional
            # create_unique_group_id: false # default is true
            # offset: earliest # default is none
            # auto_commit_offset_enabled: false # default is true

        writer:
            ## Required
            hosts:
                - 127.0.0.1:9092
            topic: queues.processor                
    writer:
        reader:
            ## Required
            hosts:
                - 127.0.0.1:9092                
            group: elc
            topic: queues.processor

            ## Optional
            # create_unique_group_id: false # default is true
            # offset: earliest # default is none
            # auto_commit_offset_enabled: false # default is true
