    writer:
        name: mongodb
        config:
            ### Required Parameters

            # The following uri assumes mongodb is running locally without any security
            mongodb_uri: "mongodb://localhost:27017/?directConnection=true"

            ### Optional Parameters
            
            # database_name: # default is event-log-collector
            # collection_name: # default is mix-event-logs

            # num_workers: 50   # Num Workers specifies how many event logs can be processed in parallel by log writer
            # rate_limit:       # Rate Limit controls how fast event logs can be written to storage
                # limit: 1000
                # burst: 10

    pipeline:
        storage_provider: kafka
        writer:
            reader:
                ## Required
                hosts:
                    - 127.0.0.1:9092                
                group: elc
                topic: queues.processor

                ## Optional                
                # offset: earliest # default is none
                # auto_commit_offset_enabled: false # default is true
